version: "3.8"
services:
    postgresql:
        image: postgres
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ./dbs/data:/var/lib/postgresql/data
            - ./dbs/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./dbs/insertions.sql:/docker-entrypoint-initdb.d/insertions.sql
    products:
        image: sgi-flask
        depends_on:
            postgresql:
                condition: service_started
        container_name: sgi-products
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${APP_POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            APP_HOST: ${APP_HOST}
            APP_PORT: ${APP_PORT_1}
            MODULES: ${APP_MODULES_1}
        ports:
            - ${APP_PORT_1}:${APP_PORT_1}
    inventory:
        image: sgi-flask
        depends_on:
            postgresql:
                condition: service_started
        container_name: sgi-inventory
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${APP_POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            APP_HOST: ${APP_HOST}
            APP_PORT: ${APP_PORT_2}
            MODULES: ${APP_MODULES_2}
        ports:
            - ${APP_PORT_2}:${APP_PORT_2}
    stores:
        image: sgi-flask
        depends_on:
            postgresql:
                condition: service_started
        container_name: sgi-stores
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${APP_POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            APP_HOST: ${APP_HOST}
            APP_PORT: ${APP_PORT_3}
            MODULES: ${APP_MODULES_3}
        ports:
            - ${APP_PORT_3}:${APP_PORT_3}
    nginx:
        image: nginx
        depends_on:
            products:
                condition: service_started
            inventory:
                condition: service_started
            stores:
                condition: service_started
        container_name: api-gateway
        ports:
            - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
        volumes:
            - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
